// vim: ft=groovy et ts=2 sw=2:

node('ansible') {
    ansiColor('xterm') {
      stage("Warming up") {
        container('ansible') {
          // Checking out public repo
          checkout scm
          // Loading library
          commonCode = load "${env.WORKSPACE}/application/pipelines/commonGroovy/common.groovy"
        }
      }
      stage("Test") {
          container('newman'){
            sh """
                  newman run https://www.getpostman.com/collections/46d50cdb62091c2e5e9d -d environment.json -r htmlextra            
               """
          }          
        } 
      }
    }
