// vim: ft=groovy et ts=2 sw=2:

node('ansible') {
    ansiColor('xterm') {
      stage("Creating Jobs") {
          container('ansible'){
            // Checking out public repo
            checkout scm
            shell 'printenv'
            jobDsl targets: 'application/pipelines/seedJob/*.groovy'
          }
      }
    }
}

