// vim: ft=groovy et ts=2 sw=2:

node('ansible') {
    ansiColor('xterm') {
      stage("Warming up") {
        container('ansible') {
          // Checking out public repo
          checkout scm
          // Loading library
          common = load "${env.WORKSPACE}/application/pipelines/commonGroovy/common.groovy"
        }
      }
      stage("Deploy") {
          container('ansible'){
            // Gathering all required variables
            common.commonVariables()
            // Checking out private repo
            common.checkoutPrivate()
            // Deploy helm
            common.deployHelm(appName)
          }
      }
    }
}
