// vim: ft=groovy et ts=2 sw=2:

node('ansible') {
    ansiColor('xterm') {
      stage("Warming up") {
        container('ansible') {
          // Checking out public repo
          checkout scm
          // Loading library
          commonCode = load "${env.WORKSPACE}/application/pipelines/commonGroovy/common.groovy"
        }
      }
      stage("Deploy") {
          container('ansible'){
            // Gathering all required variables
            commonCode.commonVariables()
            // Checking out private repo
            commonCode.checkoutPrivate()
            // Deploy helm
            // This is a workaround for flink jobs,
            // As they are using kind: Jobs and the image tag is immutable
            // We've to wait till External LB is removed.
            sh"""
              helm ls -n flink | grep ${appName} && {
                helm uninstall -n flink $appName --wait; sleep 30
              } || true
            """
            //
            commonCode.deployHelm(appName,"build/pipeline-jobs", "-e namespace=flink -e chart_path=${env.WORKSPACE}/application/helm/flink/$jobName")
          }
      }
    }
}
