name: Deploy
on:
  push:
    branches:
      - main
      - sprint-*
      - workflow
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          # aws-profile: hcx
          # role-to-assume: arn:aws:iam::131795456882:role/OrganizationAccountAccessRole
      # - uses: actions/checkout@v1

      # - name: Checkout Private Repo
      #   run: |
      #     eval `ssh-agent -s`
      #     ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
      # - uses: actions/checkout@v1
      #   with:
      #     repository: organization_name/repo_name
      #     token: ${{ secrets.ACCESS_TOKEN }}


      # - uses: shaunco/ssh-agent@git-repo-mapping # this action will configure git to use the right SSH key per each repository.
      #   with:
      #     ssh-private-key: |
      #       ${{ secrets.SSH_PRIVATE_KEY }}
      #     repo-mappings: |
      #       github.com/Swasth-Digital-Health-Foundation/DevOps


      # - uses: actions/checkout@v2
      #   with:
      #     submodules: recursive

      # - name: Check file structure
      #   run: ls -lrt ${{ github.workspace }}

      - name: Checkout private
        uses: actions/checkout@v3
        with:
          # repository: Swasth-Digital-Health-Foundation/DevOps
          repository: Swasth-Digital-Health-Foundation/DevOps
          ref: 'workflow'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: recursive
          path: DevOps

      - name: Check file structure
        run: ls -lrt ${{ github.workspace }}

      - name: 'Deploy'
        uses: bitovi/github-actions-deploy-eks-helm@v1.1.0
        # uses: vimeda/helm@v1.6.8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # cluster-role-arn: arn:aws:iam::131795456882:user/hcx
          aws-region: ap-south-1
          # aws-profile: git-deploy
          cluster-name: dev-cluster
          name: 'hcx-mock-service'
          namespace: 'dev'
          # release: hcx-mock-service
          chart-path: 'application/helm/core/hcx-mock-service/'
          config-files: 'application/helm/core/hcx-mock-service/values.yaml, DevOps/hcx/ansible/inventory/dev/group_vars/dev.yaml' #, https://github.com/Swasth-Digital-Health-Foundation/DevOps/blob/workflow/hcx/ansible/inventory/dev/group_vars/dev.yaml'
          # token: '${{ github.token }}'
          # values: |
          # name: foobar
        #        helm: helm3
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

###

