pipeline {
    agent {
        label "ansible"
    }
    options{
        ansiColor('xterm')
    }
    stages {
      stage('Run ansible') {
        steps {
            container('ansible') {
              checkout scm
              checkout(
                [$class: 'GitSCM', branches: [[name: '*/main']],
                extensions: [
                    [$class: 'RelativeTargetDirectory', relativeTargetDir: 'private'],
                    [$class: 'CloneOption', noTags: true, reference: '', shallow: true]
                ],
                userRemoteConfigs: [[
                      credentialsId: "${env.GH_REPO_CRED}",
                      url: "${env.GH_PRIVATE_REPO}"
              ]]])
              sh '''
              cd ansible
              ansible-playbook -i ../private/hcx/ansible/inventory/dev/hosts kafka.yaml 
              '''
        }
      }
    }
  }
}

